# Generated by Django 4.2.1 on 2023-05-28 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Date format should be YYYY-MM-DD or YYYY', regex='^\\d{4}(-\\d{2}-\\d{2})?$')]),
        ),
    ]
