# Generated by Django 4.2.1 on 2023-05-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0002_alter_book_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
