# Generated by Django 4.2.1 on 2023-05-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
